### ISSUE TITLE
Working directory doesn't take into account symbolic links.

### ISSUE THREAD

**Issue by Rafmaninoff** [miestasmia/unilookup#2]
I have the script in ~/git/unilookup/unilookup, but it's being run through a symlink in ~/bin/. this causes the program to not find the UnicodeData.txt file it needs to function. assuming it is in the directory that the symlink is on.

Traceback (most recent call last):
  File "/home/raf/bin/unilookup", line 97, in <module>
    main()
  File "/home/raf/bin/unilookup", line 38, in main
    data = open(os.path.join(dir, 'UnicodeData.txt'))
IOError: [Errno 2] No such file or directory: '/home/raf/bin/UnicodeData.txt'

**Comment by miestasmia** [comment]
I was unable to reproduce but I believe to have fixed it. Please reopen this issue that's not the case.
